server:
  port: 8080
girl:
  cupSize: B
  age: 18
man:
  length: 18
  age: 25
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file: G:\springboot\mylog\log.log
  level: debug
